[package]
name = "pehape-rs"
description = "PHP global functions implemented in Rust"
version = "0.0.1"
edition = "2021"
authors = ["Teknologi Umum"]
homepage = "https://github.com/teknologi-umum/pehape"
repository = "https://github.com/teknologi-umum/pehape"

[dependencies]
