name: C# PR Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths: ["csharp/**"]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./csharp
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --collect="XPlat Code Coverage"
      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          flags: csharp
