name: C# PR Check

on:
  pull_request:
    paths:
      - 'csharp/**'

jobs:
  backend:
    name: Backend
    runs-on: windows-latest
    env:
      working-directory: ./csharp
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect="XPlat Code Coverage"
      - name: Report coverage
        uses: codecov/codecov-action@v1
