name: Go PR Check

on:
  push:
    branches: ["master"]
    paths: ["go/**"]
  pull_request:
    branches: ["master"]
    paths: ["go/**"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          flags: go
