name: Ruby PR Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths: ["ruby/**"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ruby
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install dependencies
        run: bundle install
      - name: Test and report coverage
        run: bundle exec rake
        env:
          CI: true
